# Generated by Django 6.0.1 on 2026-01-31 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nid",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("nid", models.CharField(db_index=True, max_length=20, unique=True)),
                ("dob", models.DateField()),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("medical_history", models.TextField(blank=True, null=True)),
                (
                    "profile_pic_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
